const scheduleMock = [
 {
  id:1,
  date: '2023-06-19',
  time: '10:00',
  clientName: 'John Doe',
  phone: '123456789',
  email: 'email@email.com',
  service: 'Consulta',
  pet: 'Jonny',
  specie: 'Cachorro',
  breed: 'Vira-lata',
  speciality: 'Clinico Geral',
  status: 'Agendado',
  notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
 id:2,
 date: '2023-06-20',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Gato',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:3,
 date: '2023-06-20',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Gato',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:4,
 date: '2023-06-21',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:5,
 date: '2023-06-21',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:6,
 date: '2023-06-23',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:7,
  date: '2023-06-19',
  time: '10:00',
  clientName: 'John Doe',
  phone: '123456789',
  email: 'email@email.com',
  service: 'Consulta',
  pet: 'Jonny',
  specie: 'Cachorro',
  breed: 'Vira-lata',
  speciality: 'Clinico Geral',
  status: 'Agendado',
  notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:8,
 date: '2023-06-20',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Gato',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:9,
 date: '2023-06-20',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Gato',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:10,
 date: '2023-06-21',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:11,
 date: '2023-06-21',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonny',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
},
{
  id:12,
 date: '2023-06-23',
 time: '10:00',
 clientName: 'John Doe',
 phone: '123456789',
 email: 'email@email.com',
 service: 'Consulta',
 pet: 'Jonn ultimo',
 specie: 'Cachorro',
 breed: 'Vira-lata',
 speciality: 'Clinico Geral',
 status: 'Agendado',
 notes: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.'
}
];

export default scheduleMock;